name: Windows CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Restore NuGet packages
      run: nuget restore ./webapp1.sln

    - name: Build
      run: '"C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Enterprise\\MSBuild\\Current\\Bin\\MSBuild.exe" ./webapp1.sln /p:Configuration=Release'

  test:
    needs: build
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Test
      run: dotnet test ./webapp1.sln --configuration Release --collect:"XPlat Code Coverage"

  deploy:
    needs: test
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Publish
      run: dotnet publish ./webapp1.sln --configuration Release --output ./publish

    - name: Deploy to Staging
      run: |
        # Add your deployment commands here
        # For example, deploying to Azure or another platform
        echo "Deploying to staging environment"

    - name: Notify on Deployment Failure
      if: failure()
      run: echo "Deployment to staging failed. Notify the team."
